version: "3.8"
name: "yut_local"

services:
  caddy:
    image: caddy
    ports:
      - "2000:443"
      - "1999:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/etc/caddy/certs
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
