// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YoutubeUploadTracker.Api.Features.Common.Persistence;

#nullable disable

namespace YoutubeUploadTracker.Api.Migrations
{
    [DbContext(typeof(YoutubeUploadTrackerDbContext))]
    [Migration("20250524160357_MappingTable")]
    partial class MappingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YoutubeUploadTracker.Api.Features.Common.Persistence.Entity.UserYoutubeSubscriptionEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("YoutubeChannelId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "YoutubeChannelId");

                    b.HasIndex("UserId");

                    b.HasIndex("YoutubeChannelId");

                    b.ToTable("UserYoutubeSubscriptionEntity");
                });

            modelBuilder.Entity("YoutubeUploadTracker.Api.Features.Common.Persistence.Entity.YoutubeChannelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("YoutubeUploadTracker.Api.Features.Common.Persistence.Entity.UserYoutubeSubscriptionEntity", b =>
                {
                    b.HasOne("YoutubeUploadTracker.Api.Features.Common.Persistence.Entity.YoutubeChannelEntity", "YoutubeChannel")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("YoutubeChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YoutubeChannel");
                });

            modelBuilder.Entity("YoutubeUploadTracker.Api.Features.Common.Persistence.Entity.YoutubeChannelEntity", b =>
                {
                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
